cli: describe lexer and parser
askalt/information_system_arch pull request #1
Opened 2024-09-13 16:34 UTC by askalt

2024-09-13 22:24 UTC, Astronomax requested changes

2024-09-13 22:24 UTC, Astronomax commented on cli/README.md
> +catCMD  ::= PATH("cat") args
Кажется, PATH, не является терминалом. Наверное, должно быть что-то типа такого:
```
catCMD  ::= IDENT("cat") args
echoCMD ::= IDENT("echo)
wcCMD   ::= IDENT("wc") args
pwdCMD  ::= IDENT("pwd")
exitCMD ::= IDENT("exit")
procCMD ::= path args

path ::= ./IDENT(_)pathsuffix
pathsuffix ::= EPS |
         /IDENT(_)pathsuffix
```

2024-09-13 22:24 UTC, Astronomax commented on cli/README.md
> +- В конце у нас получается некоторая строка, или же готовый нетерминал `SETCMD`. Если это команда, то лексер отдает дальше `SETCMD`, иначе оборачивает строчку в `PATH` и возвращает этот нетерминал.
```suggestion
- В конце у нас получается некоторая строка, или же готовый терминал `SETCMD`. Если это команда, то лексер отдает дальше `SETCMD`, иначе оборачивает строчку в `PATH` и возвращает этот нетерминал.
```
А вообще мне не до конца эта строка понятна.

2024-09-14 07:02 UTC, askalt commented on cli/README.md
> +catCMD  ::= PATH("cat") args
Убрал упоминания `IDENT` как нетерминала, чтобы не было путаницы. Остался нетерминал `PATH(...)` - его дополнительно не парсим, так как в теории это может быть произвольная строка без формата.

```diff
-- У терминала `IDENT` есть аттрибут: непосредственная строчка идентификатор. Она задается регулярным
-выражением:
+- У терминала `PATH` есть аттрибут: непосредственная строчка путь. Аттрибут представляет из себя любую строку.
+
+- У терминала `SETCMD` есть два атрибута: `src` и `dst`, src удовлетворяет регулярному выражению:

-IDENT = [_a-zA-Z][_a-zA-Z0-9]{0,30}
+[_a-zA-Z][_a-zA-Z0-9]{0,30}

-- У терминала `PATH` есть аттрибут: непосредственная строчка путь. Аттрибует представляет из себя любую строку.
-
-- У терминала `SETCMD` есть два атрибута: `src` и `dst`, src удовлетворяет регулярному выражению для `IDENT`,


-    - При встрече неэкранированного `$`, лексер жадно читает последующий `IDENT`, берет его значение из `Env`,
+    - При встрече неэкранированного `$`, лексер жадно читает следующие символы, пока они не выходят за рамки
+    регулярного выражения для `src`, и берет значение прочитанного ключа из `Env`,
```

2024-09-14 07:03 UTC, askalt commented on cli/README.md
> +- В конце у нас получается некоторая строка, или же готовый нетерминал `SETCMD`. Если это команда, то лексер отдает дальше `SETCMD`, иначе оборачивает строчку в `PATH` и возвращает этот нетерминал.
Переписал:
```diff
-- В конце у нас получается некоторая строка, или же готовый нетерминал `SETCMD`. Если это команда, то лексер отдает дальше `SETCMD`, иначе оборачивает строчку в `PATH` и возвращает этот нетерминал.
+- В конце у нас получается некоторая строка `s`, или же готовый терминал `SETCMD`. Если это `SETCMD`, то лексер
+возвращает его, иначе возвращает `PATH(s)`.
```

2024-09-14 07:07 UTC, Astronomax approved these changes

2024-09-14 07:26 UTC, merged